/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ElectrolinerasRouteImport } from './routes/electrolineras'
import { Route as PlanificarRouteImport } from './routes/planificar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectrolinerasRoute = ElectrolinerasRouteImport.update({
  id: '/electrolineras',
  path: '/electrolineras',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanificarRoute = PlanificarRouteImport.update({
  id: '/planificar',
  path: '/planificar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/electrolineras': typeof ElectrolinerasRoute
  '/planificar': typeof PlanificarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/electrolineras': typeof ElectrolinerasRoute
  '/planificar': typeof PlanificarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/electrolineras': typeof ElectrolinerasRoute
  '/planificar': typeof PlanificarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/electrolineras' | '/planificar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/electrolineras' | '/planificar'
  id: '__root__' | '/' | '/electrolineras' | '/planificar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ElectrolinerasRoute: typeof ElectrolinerasRoute
  PlanificarRoute: typeof PlanificarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electrolineras': {
      id: '/electrolineras'
      path: '/electrolineras'
      fullPath: '/electrolineras'
      preLoaderRoute: typeof ElectrolinerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planificar': {
      id: '/planificar'
      path: '/planificar'
      fullPath: '/planificar'
      preLoaderRoute: typeof PlanificarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ElectrolinerasRoute: ElectrolinerasRoute,
  PlanificarRoute: PlanificarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
